export default ()=>{
    return [
        {
            name:'Java高级应用课程设计\n',
            teacher:'伍章俊',
            instructor:['伍章俊'],
            class:['信息管理16-1','信息管理16-2'],
            sort:'3',
            type:'2',
            demand:'1',
            count: 100,
            hour: 90,
            reserve:[
                {
                    place:'管理1号楼1403/1415',
                    week:'第12周',
                    watt:'周一',
                    time:'5-12节'
                },
                {
                    place:'管理1号楼1403/1415',
                    week:'第12周',
                    watt:'周三',
                    time:'5-12节'
                },
                {
                    place:'管理1号楼1403/1415',
                    week:'第12周',
                    watt:'周四',
                    time:'5-12节'
                },
                {
                    place:'管理1号楼1403/1415',
                    week:'第13周',
                    watt:'周一',
                    time:'5-12节'
                },
                {
                    place:'管理1号楼1403/1415',
                    week:'第13周',
                    watt:'周三',
                    time:'5-12节'
                },
            ],
            year:'2017－2018学年第二学期'
        },{
            name:'Java程序设计课程设计',
            teacher:'程浩',
            instructor:['白羽'],
            class:['信息管理16-1','信息管理16-2'],
            sort:'3',
            type:'2',
            demand:'1',
            count: 100,
            hour: 90,
            reserve:[
                {
                    place:'管理1号楼1403/1415',
                    week:'第13周',
                    watt:'周六',
                    time:'1-12节'
                },
                {
                    place:'管理1号楼1403/1415',
                    week:'第14周',
                    watt:'周六',
                    time:'1-12节'
                },
                {
                    place:'管理1号楼1403/1415',
                    week:'第15周',
                    watt:'周六',
                    time:'1-12节'
                },
                {
                    place:'管理1号楼1403/1415',
                    week:'第16周',
                    watt:'周六',
                    time:'1-12节'
                }
            ],
            year:'2017－2018学年第二学期'
        },{
            name:'Java程序设计课程设计',
            teacher:'程浩',
            instructor:['白羽'],
            class:['电子商务17-1','电子商务17-2'],
            sort:'3',
            type:'2',
            demand:'1',
            count: 100,
            hour: 90,
            reserve:[
                {
                    place:'管理1号楼1403/1415',
                    week:'第13周',
                    watt:'周日',
                    time:'1-12节'
                },
                {
                    place:'管理1号楼1403/1415',
                    week:'第14周',
                    watt:'周日',
                    time:'1-12节'
                },
                {
                    place:'管理1号楼1403/1415',
                    week:'第15周',
                    watt:'周日',
                    time:'1-12节'
                },
                {
                    place:'管理1号楼1403/1415',
                    week:'第16周',
                    watt:'周日',
                    time:'1-12节'
                }
            ],
            year:'2017－2018学年第二学期'
        }
    ]
}